DPL-395-1
sanger/limber pull request #1115
Opened 2022-07-05 13:38 UTC by harrietc52

Closes #1114 

Changes proposed in this pull request:

*
*
* ...

2022-07-12 15:23 UTC, KatyTaylor requested changes
A couple of naming things (`asset` and `batch_names`) which I think it would be good to change.

I skimmed over the Vue components as I think you said James did quite a thorough review of the javascript already.

2022-07-13 14:14 UTC, sdjmchattie approved these changes

2022-07-15 10:51 UTC, harrietc52 commented
To build the tube `LTHR-384 Pool XP` run the integration suite for heron LTHR pipeline `spec/limber/heron_lthr_pipeline_spec.rb`

2022-07-15 12:49 UTC, harrietc52 commented
Tubes:
- NT338C
- NT339D (added metadata)

2022-07-25 13:40 UTC, KatyTaylor approved these changes

2022-08-01 09:51 UTC, merged