DPL-1028: Improve pipeline graph legibility
sanger/limber pull request #1544
Opened 2024-01-12 15:03 UTC by StephenHulme

Closes #1512 

**Note:** This PR is to merge into #1543 

#### Changes proposed in this pull request

Greatly improves ease of reading the pipeline graphs

- Wrap purpose label text
- Improve legibility of plate 384 labels
- Use the better suited [ELK](https://github.com/cytoscape/cytoscape.js-elk) layout
- Prevent purposes from being dragged around
- Adjust size of the graph to fill the screen
- Small styling changes to the Key
- Show the pipeline name on edge hover
- Click on the pipeline name to filter by that pipeline

**Search view:**

<img width="831" alt="Screenshot 2024-01-12 at 15 04 45" src="https://github.com/sanger/limber/assets/135011085/61525c1c-5cb9-4acb-b277-9cf5abb43f07">

**Overall view:**

<img width="830" alt="Screenshot 2024-01-12 at 15 07 48" src="https://github.com/sanger/limber/assets/135011085/b328672e-58d0-43ec-a4b9-8ff0ed6e447d">

**Updated to show purpose properties:**

<img width="1032" alt="Screenshot 2024-01-15 at 13 33 34" src="https://github.com/sanger/limber/assets/135011085/c6873472-a51c-430f-92cb-dbe33a2b4f21">

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

2024-01-15 14:59 UTC, BenTopping commented on app/assets/stylesheets/limber/screen.scss
> -#app {
I would be careful changing this. I think some pages require extra space at the bottom. See screenshot - were options are sinking into footer. Maybe they require a fix instead.
![Screenshot 2024-01-15 at 14 59 11](https://github.com/sanger/limber/assets/54811755/4b63544b-3d9f-4472-a3bd-e1b3023da085)

2024-01-15 15:09 UTC, BenTopping requested changes
Looks good. One comment about the margin change.

2024-01-15 15:25 UTC, KatyTaylor commented
Seems like this will improve things a lot, thanks!

2024-01-15 15:26 UTC, KatyTaylor approved these changes

2024-01-18 15:14 UTC, KatyTaylor approved these changes

2024-01-19 10:15 UTC, merged