Y24-109 - Rework Limber documentation for clarity on how SequenceScape & Limber interact and are setup
sanger/limber pull request #1759
Opened 2024-07-02 10:24 UTC by SHIV5T3R

Closes #1709 

#### Changes proposed in this pull request

- Reordered the steps for setting up Limber so that one application is setup before another, clearly outlining how many terminals are needed.
- Added some detail on what some of the steps and rake tasks do.

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

2024-07-02 10:38 UTC, SHIV5T3R commented
I've changed the order of the steps so it's a little bit easier to figure out how to set things up. Any improvements needed @KatyTaylor @andrewsparkes

2024-07-08 09:51 UTC, andrewsparkes requested changes
Looks good other than clarifying the SS vs Limber relationship at the top, and that running limber:setup separately is now not required.

I did wonder about troubleshooting tips. e.g. about node versions and yarn, deleting node_modules directory and or assets:clobber. But maybe troubleshooting should be a separate section.

2024-07-08 09:51 UTC, andrewsparkes commented on README.md
> +Because Limber relies on SequenceScape as a backend, SequenceScape and it's jobs can be started first. SequenceScape **will** work standalone without Limber.
'must' be started first.
Limber **will not** work independently.
Limber is the front end for Sequencescape and handles pipeline tracking functionality used by Lab staff.

2024-07-08 09:51 UTC, andrewsparkes commented on README.md
> +   bundle exec rake limber:setup
See` lib/tasks/application.rake`
Line 13
`task post_deploy: %w[record_loader:all limber:setup]`

limber:setup is now done as part of post_deploy. It used be separate.
So you can remove this line.

2024-07-08 10:53 UTC, andrewsparkes approved these changes

2024-07-09 11:05 UTC, merged