DPL-865 handle sprint client response
sanger/limber pull request #2130
Opened 2024-12-17 09:08 UTC by dasunpubudumal

Closes #

#### Changes proposed in this pull request

- 

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

2025-01-06 11:19 UTC, BenTopping requested changes
Looks good, couple advisories. I haven't tested locally.

2025-01-06 11:19 UTC, BenTopping commented on spec/models/print_job_spec.rb
> +        "{\"data\":{\"print\":{\"jobId\":\"psd-2:68b27056-11cf-41ff-9b22-bdf6121a95be\"}}}"
Advisory `{ data: { print: { jobId: "psd-2:68b27056-11cf-41ff-9b22-bdf6121a95be" } } }.to_json` is slightly more readable

2025-01-06 11:19 UTC, BenTopping commented on spec/models/print_job_spec.rb
> +        "{\"errors\":[{\"message\":\"Variable 'printRequest' has an invalid value: Expected type 'Int' but was 'Double'.\",\"locations\":[{\"line\":1,\"column\":16}],\"extensions\":{\"classification\
same here object.to_json is more readable.

2025-01-06 11:19 UTC, BenTopping commented on spec/models/print_job_spec.rb
> +        "{\"errors\":[{\"message:\"Variable 'printRequest' has an invalid value: Expected type 'Int' but was 'Double'.\",\"locations\":[{\"line\":1,\"column\":16}],\"extensions\":{\"classification\":
same here object.to_json is more readable.

2025-01-06 11:19 UTC, BenTopping commented on app/models/print_job.rb
> +        return response_body['errors'].pluck('message').join(' - ') if response_body['errors'].present?
In the sprint response example above there is are also other error keys like `locations` and `extensions`. Are they not useful in this context?

2025-01-06 11:19 UTC, BenTopping commented on spec/models/print_job_spec.rb
> +      pj =
Can you move pj to a global/shared variable so you don't need to define it in each test.

2025-01-20 11:51 UTC, dasunpubudumal commented on spec/models/print_job_spec.rb
> +      pj =
Hi Ben, `pj` is not constant across all the examples. But I have made it global to some scenarios (in the latest commit).

2025-01-21 11:13 UTC, dasunpubudumal commented on app/models/print_job.rb
> +        return response_body['errors'].pluck('message').join(' - ') if response_body['errors'].present?
I am currently investigating a better way - if we can - to format the messages.

2025-01-21 11:48 UTC, andrewsparkes approved these changes
Nice improvements, thanks.

Not sure the user will like the 'try again later' messages, but this is much better than getting no label and nothing at all from LIMS to indicate why. And they can raise a clearer support message if needed.

2025-01-21 12:54 UTC, dasunpubudumal commented on app/models/print_job.rb
> +        return response_body['errors'].pluck('message').join(' - ') if response_body['errors'].present?
I have updated it. Please do have a look when you have time :)

2025-01-21 13:23 UTC, BenTopping reviewed
Looks good, codecov complaining about tests I have mentioned.

2025-01-21 13:23 UTC, BenTopping commented on spec/models/print_job_spec.rb
> +      response = Net::HTTPBadGateway.new(1.0, '502', nil)
Could we also test the errors for Net::HTTPUnprocessableEntity and Net::HTTPInternalServerError as they have separate routes / error messages.

2025-01-21 13:45 UTC, dasunpubudumal commented on spec/models/print_job_spec.rb
> +      response = Net::HTTPBadGateway.new(1.0, '502', nil)
I just added two more tests, but Codecov is still complaining?

2025-01-21 14:31 UTC, dasunpubudumal commented on spec/models/print_job_spec.rb
> +      response = Net::HTTPBadGateway.new(1.0, '502', nil)
Fixed it. Thanks.

2025-01-21 15:19 UTC, BenTopping approved these changes

2025-01-29 10:18 UTC, merged